title: Rayyan Ranje # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
show download: true
description: Data Analyst with 2 years of experience and a tech-savvy IT individual with a B.tech in IT, adept in Python, SQL, Excel, and possessing foundational knowledge of Power BI.
 <br><br>
  <a href="https://www.linkedin.com/in/rayyan-ranje-58b98520b/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'

